apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloudops-demo
  namespace: ai-cloud-labs
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
