apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudops-demo-config
  namespace: ai-cloud-labs
data:
  ENVIRONMENT: "development"
  LOG_LEVEL: "INFO"
  APP_NAME: "AI Cloud Labs Kubernetes Platform"
